### ISSUE TITLE
Suppression un keyword

### ISSUE THREAD

**Issue by pierr0t** [thelia-modules/Keyword#6]
Bonjour,

Apparemment on a un problème à la suppression d'un keyword. J'ai essayé direct, puis en supprimant toutes les associations existantes pour ce keyword, puis en décochant "visible", on arrive toujours sur une page /delete blanche mais le keyword n'est pas supprimé.

Pour l'instant j'ai rendu ceux que je voulais supprimer invisibles ...

Edit: j'étais sur la branche 2.0.4, je en sais plus ce que c'est maintenant ... master ?

Pierre.

**Comment by mespeche** [comment]
Il faut surement que tu utilises la dernière release.

**Comment by pierr0t** [comment]
Slt,

La dernière fois je devais télécharger de la branche 2.0.4 qui n'est 
plus là. Je prends  de la "master" maintenant ?

Le 05/01/2015 09:14, mespeche a écrit :
>
> Il faut surement que tu utilises la dernière release.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/thelia-modules/Keyword/issues/6#issuecomment-68678694>.
>


-- 
<http://www.zapilou.fr> *Pierre Chopot*
Gérant, gestion technique et développement
09 54 12 42 12 <callto:09%2054%2012%2042%2012>
www.zapilou.fr <hhttp://www.zapilou.fr>

**Comment by mespeche** [comment]
Tout dépend de la version de Thelia que tu utilises. Laquelle est-ce ?

**Comment by pierr0t** [comment]
Bonjour,

La dernière stable pour moi, la 2.0.4 .

Le 06/01/2015 09:05, mespeche a écrit :
>
> Tout dépend de la version de Thelia que tu utilises. Laquelle est-ce ?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/thelia-modules/Keyword/issues/6#issuecomment-68836872>.
>


-- 
Pierre

**Comment by mespeche** [comment]
Dans ce cas, il faut utiliser la branche thelia-2.0, les 2 dernières releases sont compatible uniquement pour Thelia 2.1.x

**Comment by pierr0t** [comment]
Bonjour,
Désolé de rouvrir cette "issue", je viens de télécharger la branche 2.0 et je constate toujours le souci signalé en haut, quand je veux effacer un mot-clé j'ai la boite modale qui me demande de confirmer et ensuite page blanche, le mot-clé n'étant pas supprimé du tout.
Pour l'instant je les dé-publient mais ce serait plus propre si je pouvais les supprimer.
Merci.
Pierre.

**Comment by mespeche** [comment]
Depuis Thelia v2.0.4 les url sont protégées par un système de token. Ce système n'est pas pris en change dans les versions 1.0 à 2.2.1 du plugin. C'est pourquoi je viens de faire une branche dédiée à la version 2.0.4 de Thelia qui correspond à la version 2.2.2 du plugin Keyword. Tu peux donc télécharger la nouvelle version et me dire si ton problème est résolu.

**Comment by pierr0t** [comment]
Bonjour,

Le 13/01/2015 16:46, mespeche a écrit :
>
> Depuis Thelia v2.0.4 les url sont protégées par un système de token. 
> Ce système n'est pas pris en change dans les versions 1.0 à 2.2.1 du 
> plugin. C'est pourquoi je viens de faire une branche dédiée à la 
> version 2.0.4 de Thelia qui correspond à la version 2.2.2 du plugin 
> Keyword. Tu peux donc télécharger la nouvelle version et me dire si 
> ton problème est résolu.
>
Bon apparemment c'est parfait, ça marche ! Problème résolu :-) Grand merci !
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/thelia-modules/Keyword/issues/6#issuecomment-69764759>.
>


-- 
<http://www.zapilou.fr> *Pierre Chopot*
Gérant, gestion technique et développement
09 54 12 42 12 <callto:09%2054%2012%2042%2012>
www.zapilou.fr <hhttp://www.zapilou.fr>

**Comment by mespeche** [comment]
Parfait, je ferme cette issue.
Merci pour l'intérêt que tu portes à ce plugin :-).
