### ISSUE TITLE
Souci avec boucle keyword_product

### ISSUE THREAD

**Issue by pierr0t** [thelia-modules/Keyword#8]
Bonjour,

J'ai un petit souci avec une boucle keyword_product qui me produit un ooops. Ma variable {$smarty.get.kw} récupère le mot-clé de l'url, si je l'affiche c'est bon mais la boucle fait un oops. Si j'utilise keyword="22" (l'id de mon keyword de test), ça ne marche pas mais ça ne crashe plus. j'ai utilisé cette technique sur des folders (à l'identique) et ça fonctionne ... une idée ?

{loop name="prodaveckw" type="keyword_product" keyword="{$smarty.get.kw}" association_order="manual_reverse"}
 {assign var="ListProdKw" value={$ListProdKw|cat:{$comma}|cat:{$ID}}}
 {assign var="comma" value=","}
{/loop}	

en fait je construis une liste csv des id de produits dans une variable ListProdKw qui ont un keyword pour ensuite faire une boucle produits qui ne sélectionne que les bons.

Pierre.

**Comment by mespeche** [comment]
Ta boucle a pourtant l'air correct. Ton "ooops" indique quoi comme message d'erreur exactement ?

Essaye de vider ton cache si c'est ta première activation du module.

**Comment by pierr0t** [comment]
Bonjour,

Oui j'aurai dû la donner tout de suite:

Adding a condition to a nonexistent join, category_associated_keyword_join. Try calling join() first. 

Pierre

**Comment by mespeche** [comment]
Voilà qui est résolu, c'était une petite erreur de copié/collé de ma part. Merci pour ton retour ;-)

https://github.com/thelia-modules/Keyword/tree/v2.4.5
